dist: trusty
sudo: false
language: cpp

common_sources: &all_sources
  - ubuntu-toolchain-r-test

addons:
  apt:
    sources:
      - *all_sources
    packages:
      - gcc-5
      - g++-5

before_install:
  - sudo wget https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp -O /usr/local/include/catch.hpp

script:
  - mkdir ./bin
  - g++-5 ./test/*.cpp -Wall -Wextra -DDEBUG -std=c++11 -I./include -lpthread -o ./bin/rua_tests_d
  - ./bin/rua_tests_d
  - g++-5 ./test/*.cpp -DNDEBUG -O3 -std=c++11 -I./include -lpthread -o ./bin/rua_tests
  - ./bin/rua_tests
