language: cpp
dist: xenial
sudo: false

matrix:
  include:
    - os: linux
      env:
        - CXXFLAGS="-std=c++11 -DDEBUG -Wall -Wextra"
      compiler: gcc

    - os: linux
      env:
        - CXXFLAGS="-std=c++11 -DNDEBUG -O3"
      compiler: gcc

    - os: linux
      env:
        - CXXFLAGS="-std=c++17 -DDEBUG -Wall -Wextra"
      compiler: gcc

    - os: linux
      env:
        - CXXFLAGS="-std=c++17 -DNDEBUG -O3"
      compiler: gcc

    - os: linux
      env:
        - CXXFLAGS="-std=c++11 -DDEBUG -Wall -Wextra"
      compiler: clang

    - os: linux
      env:
        - CXXFLAGS="-std=c++11 -DNDEBUG -O3"
      compiler: clang

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - CXXFLAGS="-std=c++17 -DDEBUG -Wall -Wextra"
      compiler: clang

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - CXXFLAGS="-std=c++17 -DNDEBUG -O3"
      compiler: clang

install:
  - sudo wget https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp -O /usr/local/include/catch.hpp

script:
  - mkdir ./bin
  - ${CXX} ./test/*.cpp ${CXXFLAGS} -I./include -lpthread -o ./bin/rua_tests
  - ./bin/rua_tests

notifications:
  email: false
