set(rua_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/../include")
add_library(rua INTERFACE IMPORTED)
target_include_directories(rua INTERFACE ${rua_INCLUDE_DIR})
if(WIN32)
	target_link_libraries(rua INTERFACE psapi)
elseif(UNIX)
	target_link_libraries(rua INTERFACE pthread)
endif()
set(rua_FOUND true)
