name: Windows

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        mkdir ./out
        cd ./out
        cmake .. -DRUA_TEST=all
        cmake --build .
        .\Debug\rua_test.exe
