name: Windows

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: build debug
      run: |
        mkdir ./out.d
        cd ./out.d
        cmake .. -DCMAKE_BUILD_TYPE=Debug
        cmake --build . --config Debug
        .\Debug\rua_test_11.exe
        .\Debug\rua_test_14.exe
        .\Debug\rua_test_17.exe
        .\Debug\rua_test_20.exe

    - name: build release
      run: |
        mkdir ./out
        cd ./out
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release
        .\Release\rua_test_11.exe
        .\Release\rua_test_14.exe
        .\Release\rua_test_17.exe
        .\Release\rua_test_20.exe
